port: 7890
allow-lan: true
mode: rule
log-level: info
unified-delay: true
clash-for-android:
    append-system-dns: false
hosts:
  mtalk.google.com: 108.177.125.188
dns:
  enable: true
  listen: 127.0.0.1:5335
  use-hosts: true
  default-nameserver: [223.5.5.5, 119.29.29.29]
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-filter: ["*.n.n.srv.nintendo.net", +.stun.playstation.net, xbox.*.*.microsoft.com, "*.msftncsi.com", "*.msftconnecttest.com", WORKGROUP, "*.lan", stun.*.*.*, stun.*.*, time.windows.com, time.nist.gov, time.apple.com, time.asia.apple.com, "*.ntp.org.cn", "*.openwrt.pool.ntp.org", time1.cloud.tencent.com, time.ustc.edu.cn, pool.ntp.org, ntp.ubuntu.com, "*.*.xboxlive.com", speedtest.cros.wr.pvp.net]
  nameserver: [tls://223.5.5.5:853, https://223.6.6.6/dns-query, https://120.53.53.53/dns-query]
  nameserver-policy: {+.tmall.com: 223.5.5.5, +.taobao.com: 223.5.5.5, +.alicdn.com: 223.5.5.5, +.aliyun.com: 223.5.5.5, +.alipay.com: 223.5.5.5, +.alibaba.com: 223.5.5.5, +.qq.com: 119.29.29.29, +.tencent.com: 119.29.29.29, +.weixin.com: 119.29.29.29, +.qpic.cn: 119.29.29.29, +.jd.com: 119.29.29.29, +.bilibili.com: 119.29.29.29, +.hdslb.com: 119.29.29.29, +.163.com: 119.29.29.29, +.126.com: 119.29.29.29, +.126.net: 119.29.29.29, +.127.net: 119.29.29.29, +.netease.com: 119.29.29.29, +.baidu.com: 223.5.5.5, +.bdstatic.com: 223.5.5.5, +.bilivideo.+: 119.29.29.29, +.iqiyi.com: 119.29.29.29, +.douyinvod.com: 180.184.1.1, +.douyin.com: 180.184.1.1, +.douyincdn.com: 180.184.1.1, +.douyinpic.com: 180.184.1.1, +.feishu.cn: 180.184.1.1}
  fallback: [tls://101.101.101.101:853,https://101.101.101.101/dns-query, https://public.dns.iij.jp/dns-query, https://208.67.220.220/dns-query]
  fallback-filter: {geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32, 127.0.0.1/32], domain: [+.google.com, +.facebook.com, +.twitter.com, +.youtube.com, +.xn--ngstr-lra8j.com, +.google.cn, +.googleapis.cn, +.googleapis.com, +.gvt1.com, +.paoluz.com, +.paoluz.link, +.paoluz.xyz, +.sodacity-funk.xyz, +.nloli.xyz,+.jsdelivr.net, +.proton.me]}

proxies:
  - {name: "LineOne",type: wireguard,server: 188.114.96.130,port: 7281,ip: 172.16.0.2,private-key: uMbl3zqTvcmwLvQ93tL3jq6AUCVrMaL2BxT8e3urUn8=,public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=,remote-dns-resolve: false,udp: true}
  - {name: "LineTwo",type: wireguard,server: 188.114.96.45,port: 8886,ip: 172.16.0.2,private-key: uMbl3zqTvcmwLvQ93tL3jq6AUCVrMaL2BxT8e3urUn8=,public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=,remote-dns-resolve: false,udp: true}
  - {name: "LineThree",type: wireguard,server: 188.114.99.74,port: 942,ip: 172.16.0.2,private-key: KIV5EsjDNA3mF11Sfedfvy9Xk8man/9MXYdJQxwffEo=,public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=,remote-dns-resolve: false,udp: true}
  - {name: "LineFour",type: wireguard,server: 188.114.99.50,port: 955,ip: 172.16.0.2,private-key: SHVqHEGI7k2+OQ/oWMmWY2EQObbRQjRBdDPimh0h1WY=,public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=,remote-dns-resolve: false,udp: true} 

proxy-groups:
  - name: SelectProxy
    type: select
    proxies:
      - Auto
      - LoadBalance
      - LineOne
      - LineTwo
      - LineThree
      - LineFour
  - name: Auto
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 1200
    tolerance: 200
    proxies:
      - LineOne
      - LineTwo
      - LineThree
      - LineFour
  - name: LoadBalance
    type: load-balance
    proxies:
      - LineOne
      - LineTwo
      - LineThree
      - LineFour
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing

rules:
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,SelectProxy
